# Appendix B - Simulation Details {#append2}

To simulate fish passing a dam, we developed an $\mathbb{R}$ software function [@R-Core-Team2020]. The function randomly samples observations from assumed probability distribution functions (pdf) with known parameters. Total unique fish, $N$, and a vector, $\omega$, containing the proportions of wild ($w$), hatchery ($h$) and hatchery no-clip ($hnc$) fish passing the dam is set to establish known "truths" of escapement by origin.

$$
\begin{aligned}
\left[N_{w}, N_{h}, N_{hnc} \right] &= N * \left[\omega_{w}, \omega_{h}, \omega_{hnc} \right]
\end{aligned}
$$

Escapement of each origin is then randomly divided across a set number of populations, $n$, by randomly drawing proportions, $\phi_{j,p}$, of origin group $j$ in each population $p$ using a Dirichlet pdf. The Dirichlet function is parameterized from a vector, $\zeta_j$, containing 1's and 0's designating populations with origin $j$ fish returning. For each population $p$, $\zeta_{j,p}$ is drawn from a Bernoulli pdf using the proportion of populations that contain each origin, $\tau_j$. Wild fish are assumed to be in all populations; $\tau_w = 1.0$. The product of sampled population proportions $\phi_{j,p}$ and fixed $N_j$ yields a random variable of abundance for each origin in each population, $N_{j,p}$. Summing across origin abundances then gives a random total population abundance, $N_p$, crossing the dam.

$$
\begin{aligned}
  \zeta_{j,p} &\sim \text{Bernoulli}(\tau_j) \\
  \left[\phi_{j,p=1},  ... , \phi_{j,p=n}\right] &\sim \text{Dir} \left(\zeta_{j,p=1},  ... , \zeta_{j,p=n} \right) \\
  N_{j,p} &= N_j * \phi_{j,p} \\
  N_p &= \sum_{j \in w, h, hnc} N_{j,p}
\end{aligned}
$$

Mean arrival date, $\bar{a}_p$, for each population returning to the dam is drawn from a normal pdf with hyper-parameters $\mu_a$ and $\sigma^2_a$. Similarly, the variance or spread in run-timing within populations is the absolute value of random variables drawn from a normal pdf with hyper-parameters $\mu_s$ and $\sigma^2_s$.

$$
\begin{aligned}
 \left[\bar{a}_p, ..., \bar{a}_n\right] &\sim \mathcal{N}(\mu_a, \sigma^2_a) \\
 \left[s_p, ..., s_n\right] &\sim \left | \mathcal{N}(\mu_s, \sigma^2_s) \right |
\end{aligned}
$$

After sampling the mean date of arrival and variances for each population, the date of arrival, $a_{i,p}$, for individual fish, $i$, within each population are drawn from a normal pdf with population parameters $\bar{a}_p$ and $s^2_p$. This simulates a random arrival day that is similar for all fish returning to the same population, regardless of origin.

$$
\begin{aligned}
 date_{i,p} &\sim \mathcal{N}(\bar{a}_p, s^2_p) \\
\end{aligned}
$$

To model different fish behavior and dam operational scenarios, seven additional attributes are randomly assigned to each individual fish. Each attribute is randomly assigned a TRUE/FALSE using a Bernoulli pdf and a fixed probability parameter. Fish passage during the day-time (i.e., during periods of window operation) is modeled using one minus the night-time passage rate ($1 - \nu$). Window observations are conditioned on fish passing during the day and being observed at a set rate, $\gamma$. Whether fish $i$ is sampled by the adult trap is modeled on the weekly set trap rate, $\delta_t$. The rate of previously PIT-tagged fish is determined by $\lambda$, and their subsequent detection at the ladder PIT antenna is governed by $\kappa$. Fallback behavior is modeled with a common rate across all populations, $\psi$. Re-ascension occurs with probability $\rho$, conditioned on fish $i$ falling back. If fish $i$ falls back and re-ascends, the entire process described above is repeated, with some time-lag between initial ascension and re-ascension that is governed by a Poisson pdf with mean = 2 days. Fish may fallback and re-ascend up to 3 times, allowing for the possibility of the same fish being counted or trapped multiple times.

$$
\begin{aligned}
  day_{i} &\sim \text{Bern}(1-\nu) \\
  window_{i} &\sim \text{Bern}(\gamma \times day_i) \\
  trapped_{i} &\sim \text{Bern}(\delta_t) \\
  tagged_{i} &\sim \text{Bern}(\lambda) \\
  ladder_{i} &\sim \text{Bern}(\kappa \times tagged_i) \\  
  fallback_{i} &\sim \text{Bern}(\psi) \\
  re-ascend_{i} &\sim \text{Bern}(\rho \times fallback_i)
\end{aligned}
$$

Simulation parameters for model evaluations were set to mimic typical escapement of spring/summer Chinook Salmon to LGD with similar origin proportions, marking rates and run timing as those observed from return years 2010 - 2015. Escapement of each origin ($N_j$) was set at 25,000 wild, 70,000 hatchery and 5,000 hatchery no-clips spread randomly across 25 populations ($n$). Of the 25 populations, each had a 1.0 probability of containing wild fish, 0.50 probability of having hatchery fish and 0.15 probability of receiving hatchery no-clip ($\tau_j$); resulting in an expected 25 wild, 12.5 hatchery and 3.75 hatchery no-clip populations. Mean arrival dates and variability were estimated from PIT-tag detection data queried from the Columbia Basin Research Data Access in Real Time ([DART](http://www.cbr.washington.edu/dart/query/pit_adult_window)) website and organized by release subbasin. Mean arrival date across all subbasins and 2010 - 2015 return years was June $19^{th}$ ($\mu_a = 171$) with a standard deviation of 13 days ($\sigma_a$). While the observed spread (i.e., variance) of arrival dates within subbasins was determined to have a mean ($\mu_s$) of 22 days and a standard deviation of 7 days ($\sigma_s$).

For the specific simulated scenarios, we were interested in STADEM model estimates of origin specific escapement from the combinations of two separate trapping rates, two fallback, re-ascension and night-passage combinations and three window count error rates; resulting in twelve different scenarios. First, trapping rates were set static at 0.15 across all weeks for six scenarios to mimic an optimum trap operation for an expected return of 25,000 wild fish (i.e., trap $\approx$ 4,000 wild fish). For the remaining six scenarios, trapping rates for weeks 30, 31 and 32 (i.e., July $22^{nd}$ to August $11^{th}$) were changed to 0.00 to test STADEM sensitivities to potential trap shut downs similar to those observed in 2013, 2014 and 2015 [@Ogden2014; @Ogden2016a; @Ogden2016b]. To simulate and control the number of re-ascending and night-time passing fish to model response, we altered fallback and night-time passage rates while holding the re-ascension rate constant at $\rho = 1.0$. Altering fallback rates and holding re-ascension constant allowed for a more simple control of the number of fish re-ascending; because the number of re-ascending fish is a function of the number of fallbacks and the re-ascension rate. Six scenarios had equal rates of fallback and night-time passage set at $\psi = \nu = 0.06$ [@Boggs2004] which means other estimator assumptions [@Schrader2013]. The other six scenarios set fallback at $\psi = 0.10$ and night-time passage at $\nu = 0.05$ to create a 5.0% positive bias of unique fish at the window. A potential 5.0% weekly bias was determined from PIT-tag data and within the range of observed weekly difference for return years 2010 - 2015 (Figure \@ref(fig:night-reasc-diff-fig)). Finally, we desired to test the sensitivities of STADEM to potential rates of window count error; 0%, 5% and 10% [@Hatch1994]. To simulate window count error, we assumed the observed daily count was a random variable from a normal distribution with a mean equal to the true daily count, and a standard deviation equal to the applied error rate (i.e., 0%, 5%, 10%) multiplied by the true daily count. This method simulated observed counts as unbiased, and allowed for possible under and overcounts at the window.

All code for simulating data and fitting STADEM to that data can be found at [https://www.github.com/KevinSee/ManuscriptSTADEM]([https://www.github.com/KevinSee/ManuscriptSTADEM]). 
