# Appendix A - STADEM Model Description {#append1}

## Total and Weekly Escapement 

Escapement at Lower Granite Dam (LGD) is estimated by combining two independent observations, trap catches and window counts, of the true number of fish crossing the dam in a state-space model [@royle2008hierarchical] with a weekly time-step. Both are assumed to be corrupted observations of the true unknown number of fish crossing LGD each week. The log of the true number of fish crossing ($X_t$), is modeled as a random walk process [@Shumway2010].

$$
\begin{aligned}
  \ln \left( X_{t} \right) &= \ln \left( X_{t-1} \right) + e_t \\
  e_t &\sim \mathcal{N}(0, \sigma^2_X)
\end{aligned}
$$

The number of fish caught in the trap, $Y^T_t$, for week $t$ is modeled as a binomial process based on the unknown true trap rate that week, $\nu_t$, and the unknown true number of fish crossing the dam that week, $X_t$. The estimate of the true weekly trap rate is derived based on previously PIT-tagged spring/summer Chinook and steelhead who are crossing LGD that week, using a Lincoln-Peterson mark-recapture model [@Seber2002]. The fish, from both species, caught in the trap that week are considered the "mark" group ($m_t$), and all the previously PIT tagged fish who are detected at the upper end of the LGD fish ladder that week are considered the second "capture" group, $M_t$ (which includes recaptures of the the "marked" fish). The proportion of previously marked fish that are caught in the adult trap, $m/M$ can be modeled with a binomial distribution using the same trap rate parameter, $\nu_t$. Although the group of previously PIT tagged fish is not assumed to be representative of the overall run, the rate at which they are caught in the trap should be the same rate that the overall run experiences. The more tagged fish crossing the dam in a particular week, the more certain we can be of the true trap rate.

$$
\begin{aligned}
  m_t &\sim \text{Bin} \left( \nu_t, M_t \right) \\
  Y^T_t &\sim \text{Bin} \left( \nu_t, X_t \right) \\
\end{aligned}
$$

The number of fish counted at the window, $Y^W_t$, is modeled as a (potentially) over-dispersed negative binomial process, with an expected value of $X_t^{day}$, the number of fish crossing the dam while the window is open. This is simply the total number of fish crossing that week, $X_t$, multiplied by the proportion of fish crossing while the window is open for counting, $\theta_t$, calculated on a weekly basis. In the formula below, $p_t$ is the proportion of fish observed at the window and $r$ is the shape parameter. If $r$ is estimated to be small it provides evidence for over-dispersion, and as it grows very large, the negative binomial distribution behaves like a Poisson distribution.

$$
\begin{aligned}
  X_t^{day} &= X_t * \theta_t \\
  p_t &= \frac{r}{\left( r + X_t^{day} \right)} \\
  Y^W_t &\sim \text{NegBin} \left( p_t, r \right) \\
\end{aligned}
$$

Thus, the unknown true number of fish crossing LGD each week, $X_t$, is estimated from two different data source: window counts and fish sampled in the trap. The window counts provide an estimate (with some potential observer error) of the fish crossing during daytime hours, while the fish in the trap, when expanded by the estimated true trap rate, provide an estimate of the total fish crossing that week. For weeks when we have a more precise estimate of the trap rate (i.e. weeks when lots of previously PIT tagged fish are crossing LGD), STADEM will tend to favor the estimate of total escapement based on the trap data, whereas when that trap rate is more uncertain (e.g. fewer PIT tagged fish to use in estimating the trap rate), STADEM will rely more on the window counts to estimate total escapement. During peak run times, when lots of fish are crossing LGD, estimates based on trap data and trap rates will be more precise, while estimates from the window counts may have more observation error due to so many fish passing the window. For weeks when the trap is down, STADEM relies exclusively on the window counts and nighttime passage data, but there will be more uncertainty in the estimates.

## Day-time Passage and Re-ascension Rates

There are two other processes that must be accounted for, first, the proportion of fish that cross the dam while the window is closed for counting (nighttime passage rate), and the second, the proportion of fish that are crossing the dam multiple times (re-ascension rate) and therefore potentially double-counted. Both rates can be estimated from previously PIT tagged fish that are crossing the dam each week.

The proportion of fish passing the window during non-operational hours, nighttime passage rate, is just the complement of the rate of fish passing during the day when the window is operating. The daytime passage rate for week $t$, $\theta_t$, is modeled as a random walk process and estimated from a binomial distribution based on the number of PIT tags observed to cross the dam during operational hours, $y^{day}_t$, and the total number of PIT tags observed to cross the dam at any point that week, $N_t$ [@Shumway2010].

$$
\begin{aligned}
  y^{day}_t &\sim \text{Bin} \left(\theta_t, N_t \right) \\
  \text{logit} (\theta_{t}) &= \text{logit} \left( \theta_{t-1} \right) + g_t \\
  g_t &\sim \mathcal{N}(0, \sigma^2_\theta) \\
\end{aligned}
$$

The number of total fish crossing Lower Granite differs from the number of unique fish crossing Lower Granite because some fish fallback and re-ascend the dam. These fish are potentially double-counted at the window, and have the potential to be caught in the fish trap more than once. The number of tags known to be re-ascending the dam each week, $y^{reasc}_t$, is modeled as a binomial process based on the estimated re-ascension rate, $\eta_t$, and the total number of tags crossing the dam that week, $N_t$. The logit of the re-ascension rate is modeled as a random walk process similar to day-time passage [@Shumway2010].

$$
\begin{aligned}
  y^{reasc}_t &\sim \text{Bin} \left(\eta_t, N_t \right) \\
  \text{logit} \left( \eta_{t} \right) &= \text{logit} \left(\eta_{t-1} \right) + f_t \\
  f_t &\sim \mathcal{N}(0, \sigma^2_\eta)
\end{aligned}
$$

## Origin Proportions

After estimating the total number of fish to have crossed Lower Granite each week, $X_t$, the total must be further refined into the number of wild fish, $X_{w,t}$, hatchery clipped fish, $X_{hc,t}$ and hatchery no-clip fish, $X_{hnc, t}$. This is done by estimating a weekly origin proportion vector, $\omega_t$ based on the random sample of fish caught in trap that week, $Y^T_t$. The observed number of wild, $Y^T_{w,t}$, hatchery clipped, $Y^T_{hc,t}$, and hatchery no-clip, $Y^T_{hnc,t}$, fish caught in the trap that week is assumed to come from a multinomial distribution with probability vector $\omega_t$. The log-odds ratio of the proportions in $\omega_t$, in relation to the proportion of clipped hatchery fish, $\omega_{hc,t}$ is modeled as a random walk, so it can change through time. This allows the proportions of wild, hatchery clipped and hatchery no-clip fish to shift throughout the season, based on the data available from the fish trap. 

$$
\begin{aligned}
  \left( Y^T_{w,t}, Y^T_{hc,t}, Y^T_{hnc,t} \right) &\sim \text{Multinom} \left( \omega_t, Y^T_t \right) \\
  \omega_t &= \frac{\exp(\phi_t)}{\sum{\exp(\phi_t})} \\
  \phi_{hc,t} &= 0 \\
  \phi_{w,t} &= \ln \left( \frac{\omega_{w,t}}{\omega_{hc,t}} \right) \\
  \phi_{hnc,t} &= \ln \left( \frac{\omega_{hnc,t}}{\omega_{hc,t}} \right) \\
  \phi_{w,t} &= \phi_{w, t-1} + d_{w,t} \\
  \phi_{hnc,t} &= \phi_{hnc, t-1} + d_{hnc,t} \\
  d_{w,t} &\sim \mathcal{N}(0, \sigma^2_\omega) \\
  d_{hnc,t} &\sim \mathcal{N}(0, \sigma^2_\omega) \\
\end{aligned}
$$

Finally, the number of unique fish crossing Lower Granite each week, $X_{w,t}$, is the product of the total fish crossing that week, $X_t$ multiplied by one minus the re-ascension rate, $(1 - \eta_t)$, and the origin proportion vector, $\omega_t$.

$$
\begin{aligned}
  \begin{bmatrix} X_{w,t} \\ X_{hc,t} \\ X_{hnc,t} \end{bmatrix}
  &= X_t * (1 - \eta_t) * \begin{bmatrix} \omega_{w,t} \\ \omega_{hc,t} \\ \omega_{hnc,t} \end{bmatrix}
\end{aligned}
$$

## Model Fitting

The model was fit using the JAGS program [@R-rjags], run with R software [@R-Core-Team2020]. Variance parameters $\sigma_X, \sigma_\eta, \sigma_\theta$, and $\sigma_\omega$, as well as the initial abundance, $X_1$, and the overdispersion parameter of the negative binomial, $r$, were given half-Cauchy priors with mean of 0 and scale of 100. The initial day-time passage and re-ascension rates, $\theta_1$ and $\eta_1$ were given Uniform(0,1) priors. Finally, $\phi_{w,1}$ and $\phi_{hnc,1}$ were given priors of Uniform(-3,3), in an effort to make $\omega_1$ as uniformative as possible.
